---
title: 'The Book of R: Chapter 2'
author: "gdolwell"
date: "July 21, 2017"
output: html_document
---

##Notes
###Logaritmic Expressions
```{r}
log(x=243, base=3)
```
Default natural log (base e)
```{r}
log(1)
```
***
###Vectors
vectors are not pointers
```{r}
v1<-3
v2<-c(v1, v1)
v1<-5
```
```{r echo=FALSE}
v2
```
####Creating vectors
Note: seq function includes the [end, points] in claculations.
Note: when subsetting and/or selecting elements with in a vector R starts counting at 1 not 0.

```{r}
5:10
seq(from=3, to=27, by=3)
seq(from=2, to=10, length.out=10)
seq(from=100, by=-10, length.out=10)
rep(x=c(1, 2), times=3)
rep(x=c(4, 5, 6), each=2)
sort(x=c(2, 5, 1, 7, 4, 9, 3, 1), decreasing=TRUE)
length(x=1:15)
ex1 <- 2:19
length(ex1)
ex1[1]
ex1[0]
ex1[19]
ex1[5:8]
ex1[-(1:9)]
ex1[c(1, 3, 5)]
ex1<-c(0, 1 ,ex1)
ex1
```
***
##Exercises
###Exercise 2.1
a.  
```{r}
a <- 2.3
(6*a+42)/(3^(4.2-3.62))
```
b.  
```{r}
(-4)^2+2
```
c.  
```{r}
x<-c(25.2, 15, 16.44, 15.3, 18.6)
sqrt(mean(x)/2)
```
d.  
```{r}
x2<-log(0.3)
```
```{r echo=FALSE}
x2
```
e.  
```{r}
exp(x2)
```
f.  
```{r}
-0.00000000423546322
```
***
##Exercise 2.2
a.
```{r}
x3<-3^2*4^(1/8)
```
b.
```{r}
x3<-x3/2.33
```
```{r echo=FALSE}
x3
```
c.
```{r}
x4<-8.2*10^-13
```
d.
```{r}
x3*x4
```
***
##Exercise 2.3
a.
```{r}
s1<-seq(from=5, to=-11, by=-0.3)
```
```{r echo=FALSE}
s1
```
b.
```{r}
s1<-sort(s1, decreasing=FALSE)
```
```{r echo=FALSE}
s1
```
c.
```{r}
s2<-rep(rep(c(-1, 3, -5, 7,-9 ), times=2), each = 10)
sort(s2)
```
d.
```{r}
s3<-c(seq(6:12), rep(5.3, times=3), -3, seq(from=102, to=length(s2), length.out=9))
```
```{r echo=FALSE}
s3
length(s3)
```